"""add user_robot_access table

Revision ID: 340c2e71c85c
Revises: 6aba335e
Create Date: 2026-10-01 21:07:54.767965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340c2e71c85c'
down_revision: Union[str, None] = '6aba335e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_robot_access',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('robot_id', sa.CHAR(length=36), nullable=False),
    sa.Column('granted_by', sa.CHAR(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'robot_id')
    )
    op.create_index('ix_ura_robot_id', 'user_robot_access', ['robot_id'], unique=False)
    op.create_index('ix_ura_user_id', 'user_robot_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ura_user_id', table_name='user_robot_access')
    op.drop_index('ix_ura_robot_id', table_name='user_robot_access')
    op.drop_table('user_robot_access')
    # ### end Alembic commands ###
